### ISSUE TITLE
Make full use of enhanced bibliographic support

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#312]
_Pleiades_ now has support for linkage to bibliographic records in a _Zotero_ library, to include on-demand import of key, work-level fields from _Zotero_ records into individual citations (aka references). Now we need to consolidate and fully exploit these improvements. The following tasks remain:

- [x] Update [Citation Guide](https://pleiades.stoa.org/help/citation-guide) to provide guidance on constructing new-style references in _Pleiades_.
- [ ] Remove old-style examples from the Citation Guide and ensure that there is a corresponding record in the [Pleiades Zotero Library](https://www.zotero.org/groups/2533/pleiades) for each of them.
- [ ] Create new examples in the Citation Guide for problematic works
- [ ] Identify references that cite works not yet included in the Pleiades Zotero Library and expand it to include them. 
- [ ] Identify existing references that are not making use of _Zotero_ records and update them programmatically to do so.
- [ ] Modify code for _Pleiades_ references so that the formatted citation field is presented in the edit form as an editable "Rich Text" field.
- [ ] Develop and automate repeatable process to check references for validity and link rot.
- [ ] Develop and automate repeatable process using the [Internet Archive's Wayback API](https://archive.org/help/wayback_api.php) to ensure that all on-line works and subsections thereof (i.e., individual web pages) have been submitted for archiving.
- [ ] Generate individual GitHub tickets and associated user stories for the above tasks.

cc & h/t to @rmhorne
