### ISSUE TITLE
discovery: can pleiades.workspace be eliminated?

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#384]
Parent epic: #372 
Product: [pleiades-workspace](https://github.com/isawnyu/pleiades-workspace)
Content types affected:
 - Workspace
 - Workspace Folder
 - Workspace Collection

The pleiades-workspace product is not, to my knowledge, actively used any longer by the Pleiades community. The purpose of this ticket is to investigate dependencies etc. in order to see if it would be quicker and easier to remove the entire product from the Pleiades buildout and to either delete or migrate to something else the remaining content types (since we're moving away from archetypes in order to go to Plone 5 and Python 3). 

So, we need:

 - [ ] list of steps necessary to completely remove the product from the buildout
 - [ ] list of all pleiades-workspace content items currently in the db
 - [ ] list of code dependencies elsewhere in the Pleiades stack that would have to be modified to deal with removal of the product
 - [ ] list of indexes, catalogs, or other zope things that would need to be adjusted, modified,  deleted, or migrated
 - [ ] anything else we should take into consideration before deciding whether to remove this product or not
 - [ ] engineering opinion as to whether removing the product and addressing all the above would be more or less work than upgrading the product to Dexterity and (eventually) Python 3.
