### ISSUE TITLE
discovery: can "Feature" and "Feature Collection" be eliminated? 

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#386]
Parent epic: #372 
Product: [PleiadesEntity](https://github.com/isawnyu/PleiadesEntity)

To my knowledge, the "Feature" and "Feature Collection" content types defined by the PleiadesEntity product are no longer actively used by the Pleiades community as they reflect an earlier stage in the development of our data model, now eclipsed by the quad of "place", "name", "location" and "connection" (although there may be a fair bit of content cruft drifting around in the database). Anyway, what would it take to eliminate the "Feature" and "Feature Collection" content types entirely and delete or migrate the existing content? Here are some key considerations:

 - [ ] list of steps necessary to completely remove the "Feature" and "Feature Collection" types from the PleiadesEntity product
 - [ ] list of all "Feature" and "Feature Collection" content items currently in the db
 - [ ] list of code dependencies elsewhere in the Pleiades stack that would have to be modified to deal with elimination of these content items
 - [ ] list of indexes, catalogs, or other zope things that would need to be adjusted, modified,  deleted, or migrated
 - [ ] anything else we should take into consideration before deciding whether to eliminate these content types or not
 - [ ] engineering opinion as to whether eliminating the "Feature" and "Feature Collection" content types, including addressing all the above would be more or less work than upgrading the content types to Dexterity and (eventually) Python 3.
