### ISSUE TITLE
upgrade plone

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#49]
From [the Pleiades 3 proposal narrative](http://pleiades.stoa.org/files/pleiades-3-2015/proposal.pdf), pages 4-5:

> Offloading the consumer mission as outlined above will immediately decrease some of the load on Plone, which will continue to provide the interactive editing and reviewing functions essential to the Pleiades publication workflow. By upgrading to the latest version of Plone, we will gain more performance improvements that have been added to the code base since the version we currently use was released. 

Now tracking specifics for implementation of this deliverable in #51 (upgrade and improve webapp performance). Keeping this issue open until we've addressed everything in #51 and feel this deliverable has been met for reporting purposes.

**Comment by davisagli** [comment]
I started working on this in the `jazkarta-plone4` branch of pleiades3-buildout.

I'm able to run buildout. Next step is to fix import errors for things that have moved so we can start the instance and run tests.

We should talk at standup tomorrow about our strategy for testing and deploying the upgraded site.

**Comment by davisagli** [comment]
One blocker is the use of `zgeo.*` packages which are not compatible with Plone 4 and no longer have active repositories.

Sean suggested switching to `collective.geo`, parts of which were based on the `zgeo` packages, and which has been better maintained and has repositories in the github collective.

Some tasks necessary to do that are:
- [ ] Change all uses of `zgeo.geographer.interfaces.IGeoreferenced` to its new location at `collective.geo.geographer.interfaces.IGeoreferenced`
- [ ] Make sure that existing zgeo annotations will still be found, either by migrating them to the new `collective.geo.geographer.georeference` annotation key, or by patching `collective.geo.geographer.geo.KEY` so that it will continue to read/write in the old annotation.
- [ ] Remove dependencies on `zgeo.plone.geographer` (it really only adds `zgeo_geometry` to the catalog metadata, and Pleiades overrides that anyway).
- [ ] Update `pleiades.kml` to use `collective.geo.kml` instead of `zgeo.kml` and `zgeo.plone.kml`.
- [ ] Update `pleiades.atom` to include the parts of `zgeo.atom` and `zgeo.plone.atom` that it needs (there doesn't appear to be a `collective.geo` equivalent of `zgeo.atom`).

**Comment by paregorios** [comment]
@davisagli should this issue be assigned to you?

**Comment by davisagli** [comment]
More todo items:
- [ ] fix display of user fullnames in listings
- [ ] what happened to openid login?
- [ ] re-apply Pleiades search customizations to Plone's revised search view
- [ ] fix tests
- [ ] find and fix templates that are still assuming globally defined variables
