### ISSUE TITLE
upgrade and improve webapp performance

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#51]
Upgrade Plone and improve performance. 

Relevant Pleiades 3 deliverables:

* #49: upgrade plone

For running the actual P4 upgrade deployment see: #69: Launch Checklist for Plone 4 upgrade

Associated/subordinate issues:

- [x] #52: modify maps code to fetch json from separate URI rather than using encoded URL in page link
- [x] #57: missing location and name lists on staging
- [x] #59: homepage map not working
- [x] #60: missing upgrade steps
- [x] #61: Map styles broken on place view
- [x] #62: Credits not working
- [x] #63: Topics show too many tabs
- [x] #66: Convert LDAP users to standard Plone users
- [x] #67: Missing pieces of place view
- [x] #68: Content type icons are broken
- [x] #70: set up plone.app.caching
- [x] #71: cannot create a new "place"
- [x] #72: "representative point" doesn't show on place map
- [x] #73: copyright character getting munched on creation
- [x] #74: some users in p4 staging have missing/broken names
- [x] #77: edit tabs poorly positioned
- [x] #78: radio button and combo box groups positioned oddly on edit forms
- [x] #79: Map icons are broken on working copies of places
- [x] #80: place map doesn't autozoom on working copy checkout
- [x] #82: location icons are broken in ```/recently_modified```
- [x] #83: pdf icons are broken in ```/docs/reports```
- [x] #85: determine cause of CPU usage spikes
- [x] #86 advanced search link destination differs from production

**Comment by alecpm** [comment]
I've got a few findings and possible fixes related to performance that I'd like to summarize here and get some feedback on before committing/releasing:

1) There are a few places in `place_view.pt` with `tal:condition` statements that check a content object, causing the object to be silently rendered to check the condition.  Adding `nocall:` to those will ensure that doesn't happen.  It appears this only occurs when looking at a working copy (the baseline version is checked/rendered), so it shouldn't affect rendering time for the published place, but will quadruple rendering time when viewing working copies.  This is likely to affect other templates as well, so I will review all the content views for similar issues.  At some point, I was seeing triple rendering of `base_view` for a published place on the production debug instance, but I'm not seeing that any more on production or on my local dev instance; so there may be some other related inefficiencies lurking.

2) In the `head` element of the ``place_view.pt`` there are four `link` tags (with `rel` set to `where`, `baseline-where`, `connections` and `r-where`) whose `href` attributes are set to JSON values using data URIs.  From what I can tell, there's nothing in-page which is making use of this inlined JSON; so it seems odd to render it in-page rather than having the `href` attributes point to normal HTTP URIs that simply render the JSON when followed.  These inline JSON renderings are very expensive, particularly the `connections` JSON.  It seems likely that only a small portion of page views make use of this hidden data, and any tools that do would probably simply follow HTTP URIs without modification.  Is there a critical reason to render these inline inside of `head`?

Those are both pretty trivial fixes, which will make a tremendous difference in page rendering time for Places (and possibly other types, once I see if there are similar issues there).  Additionally, there are inefficiencies in the JSON views themselves (which become less directly relevant if those views aren't being rendered inline in the HTML), which point to other avenues for significant optimization:

3) The connections JSON view is extraordinarily slow (>60 seconds for Roma with profiling on), and much of the time seems to be related to manipulating the temporal attestations vocabulary.  There are probably a number of things we could do to speed that up, including applying some intermediate internal caching and lookup optimizations for the vocabulary, but I recall this is an area where you may already be  hoping for a complete re-architecting of the time periods along with a move away from ATVM.  If that's the case, it may not be worthwhile to spend too much time optimizing that area assuming we can safely stop rendering this JSON inline in the HTML, and the JSON data isn't used frequently.

4) All the JSON views have a variety of inefficiencies in terms of how they lookup content and use the catalog which can probably be cleaned up.  Again, this will be less critical if we don't need to render the JSON inline in the HTML, but it will make eventual full JSON export more reasonable.  It's likely the non-JSON export views have similar issues.

**Comment by davisagli** [comment]
1 sounds non-risky to go ahead and change in production. For 2 let's see if @paregorios knows what that's used for first.

**Comment by alecpm** [comment]
Indeed that's the plan, though 1 doesn't offer much benefit for non working-copy content, and 2 basically solves the whole performance problem on its own.  3 and 4 become much more important if we can't do 2.

**Comment by paregorios** [comment]
I think early versions of the maps on place and location used those pre-packaged json bits. I'm not sure if they do now, but will go look.

**Comment by davisagli** [comment]
Ah yeah, it looks like they are used in https://github.com/isawnyu/PleiadesEntity/blob/master/skins/PleiadesEntity/context_map.js, which doesn't appear to be actually used anywhere.

**Comment by davisagli** [comment]
Oh, but place_map.js is still used, and it uses the `where`, `baseline-where`, and `connections` json.

**Comment by paregorios** [comment]
That would be it.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
I'm still not convinced that's a good reason to render the JSON in the page rather than let the map fetch the data via HTTP.  I'd suggest it's better to have the page appear quickly and then have the connections fill in after, then to render all that JSON inside a data-url.  It should be fairly trivial to alter that getJSON call to asynchonously follow the links.  From there we can optimize the connections JSON (primarily through changes to timer periods) and other calls.

**Comment by alecpm** [comment]
@paregorios Any thoughts on optimizing the time periods.  I can probably do a lot to speed up the stuff that's already there (there seem to be some fairly obvious inefficiencies), but if the plan is to re-architect that system, it might not be worthwhile to do so.

**Comment by paregorios** [comment]
@alecpm I think your sense about modifying what the map does is right; we need to get those pages loading faster. 

Time periods: I think we are serious about (1) getting rid of ATVM, and (2) drastically reducing the number of time periods in the vocab (but leaving oddball values in place in individual content item value fields (or some such).

**Comment by paregorios** [comment]
So, do we need to break out two separate issues from here:

1. modify place_map.js (and probably also in locations somewhere) to fetch json from separate URI rather than using encoded URL in page link
2. rearchitect time periods vocabulary and associated mechanisms

**Comment by alecpm** [comment]
Yes, I think that's the way to go.  I've already got a partial implementation of your 1) along with my 1) above, so feel free to assign that one to me.  For 2) we'll probably need to work out a plan of attack based on the TBD requirements for this feature, but there may be some preliminary optimizations we can make independent of the eventual storage for the vocabulary.

**Comment by paregorios** [comment]
JSON URL refactoring and associated maps modifications now moved to a separate issue: #52

**Comment by alecpm** [comment]
Items 1) and 4) from my list have been implemented and applied to staging, along with item 2) which is covered by issue #52.

**Comment by skleinfeldt** [comment]
@paregorios I updated the checklist - only #92 remains, need to decide if it is in or out of the P4 upgrade milestone.

**Comment by paregorios** [comment]
I just removed #92 from the checklist.
