### ISSUE TITLE
Launch checklist for Plone 4 upgrade

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#69]
re #49

- [x] Pin revisions of dev checkouts
- [x] Deploy Pleiades 4 to new server
- [x] Set up migration instance on production server
- [x] Disable access to production site (or make readonly) -- add notice to top of main_template, disable PAS authentication plugins
- [x] Export users using /home/zope/pleiades/p3-four/zopectl-scripts/export-users.py
- [x] Copy data from production server to migration instance (Data.fs, blobs)
- [x] Deactivate CacheSetup
- [x] Deactivate Poi (need to disable link integrity checks for this, and delete the tracker folder first)
- [x] Deactivate LDAP (and delete acl_users/ldap)
- [x] Deactivate plone.app.openid
- [x] Deactivate contentratings
- [x] Remove all customizations from portal_view_customizations and the custom folder
- [x] Import users using run_scripts/import_users.py
- [x] Copy data to isaw1.atlantides.org
- [x] Run Plone upgrade steps (note: we need David's fix to the plone.app.folder migration savepoint counter, and to avoid updating metadata in _recursiveUpdateRoleMappings, and to get relative icon path in updateIconsInBrains)
- [x] Run pleiades.policy upgrade steps
- [x] Make sure Place has default portal_diff configuration
- [x] Make sure plone.app.caching is enabled
- [x] Tom: Update DNS

**Comment by paregorios** [comment]
I'm keeping this ticket open and moving it to the post deployment milestone since there's still the matter of sorting the pleiades.stoa.org DNS with UKY, and that's my responsibility. 

@davisagli I note there's one un-checked task above.

**Comment by davisagli** [comment]
All done
